# -*- coding: utf-8 -*-
"""Mc donalds app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HWXqm-D6tlCDzrYxIWBeik1f8YTvLl0
"""

import streamlit as st
import joblib
import numpy as np

st.title("🔍 Upload and Use Pickle Model")

# Step 1: Upload the pickle file
uploaded_file = st.file_uploader("Upload your model (.pkl or .joblib)", type=["pkl", "joblib"])

if uploaded_file is not None:
    # Step 2: Load the model
    model = joblib.load(uploaded_file)
    st.success("✅ Model loaded successfully!")

    # Step 3: Take input data from user
    st.subheader("Enter Input Features for Prediction")
    input_data = st.text_input("Enter comma-separated values (e.g. 5.1,3.5,1.4,0.2)")

    if st.button("Predict"):
        try:
            # Convert string input to numpy array
            features = np.array([list(map(float, input_data.split(',')))])

            # Make prediction
            prediction = model.predict(features)
            st.success(f"✅ Prediction: {prediction[0]}")
        except Exception as e:
            st.error(f"⚠️ Error during prediction: {e}")
else:
    st.info("👆 Please upload your trained model file to begin.")